# Simple Railway configuration
[deploy]
startCommand = "gunicorn --worker-class gevent -w 1 --bind 0.0.0.0:$PORT wsgi:app"
healthcheckPath = "/health"
healthcheckTimeout = 120

[env]
PYTHON_VERSION = "3.11.9"
PORT = "5000"
FLASK_ENV = "production"