# Railway.app deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
SECRET_KEY = { generate = true }