# Railway.app deployment configuration - Force Docker build
[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = { default = "5000" }
FLASK_ENV = { default = "production" }
SECRET_KEY = { generate = true }