# Simple Railway configuration
[deploy]
startCommand = "gunicorn --workers 1 --bind 0.0.0.0:$PORT wsgi:app"
healthcheckPath = "/health"
healthcheckTimeout = 120

[env]
PORT = "5000"
FLASK_ENV = "production"