# Render deployment configuration
services:
  - type: web
    name: pong-royale-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production